---
title: "Big Ten Baseball Standings Predictor"
author: "Kyle Gilbert"
date: "2025-04-08"
output: github_document
---

```{r}
#| message: false
#| warning: false
#| echo: false

# Import packages
library(dplyr)
library(tidyr)
```

```{r}
#| warning: false
#| message: false
#| echo: false

### DATA COLLECTION

# Set working directory
setwd(dir = "~/Github/pitch-predictor/data")

# List data files
files <- list.files(path = "~/Github/pitch-predictor/data")

# Initialize data frame 
data <- data.frame()

# Load files
for (i in 1:length(files)) {
  temp <- read.csv(files[i], header = TRUE)
  data <- rbind(data, temp)
}

# Remove temp variables
rm(temp, i, files)
```

```{r}
#| message: false
#| warning: false
#| echo: false

### DATA CLEANING

# Subset data frame
data <- data[,-c(3,7,11,14,28,47:57,72:73,75,77:100,110:167)]

# Convert columns to factor
data[,c(3,4,6,9,11:23)] <- lapply(data[,c(3,4,6,9,11:23)], factor)

# Set "Undefined" level to NA
levels(data[,16])[levels(data[,16]) == "Undefined"] <- NA

# Replace empty strings with NA
data[data == ""] <- NA

# Drop NA pitch types
data <- data %>% filter(!is.na(data[,16]))
data <- data %>% filter(!is.na(data[,2]))
```

```{r}
#| message: false
#| warning: false
#| echo: false

### DATA TRANSFORMATION

# Compute play result counts ∀ pitchers
play_data <- data %>% 
  count(Pitcher, PlayResult) %>% 
  pivot_wider(
    names_from = PlayResult,
    values_from = n,
    values_fill = 0
  )

# Count strikeouts & walks ∀ pitchers
count_data <- data %>% 
  count(Pitcher, KorBB) %>% 
  pivot_wider(
    names_from = KorBB,
    values_from = n,
    values_fill = 0
  )

# Count hit-by-pitches ∀ pitchers
pitch_data <- data %>% 
  count(Pitcher, PitchCall) %>% 
  pivot_wider(
    names_from = PitchCall,
    values_from = n,
    values_fill = 0
  )

# Count innings pitched ∀ pitchers
inning_data <- data %>% 
  group_by(Pitcher, Inning, Date) %>% 
  summarise() %>% 
  ungroup() %>% 
  count(Pitcher, name = "Innings")

# Join individual pitcher data
pitcher_data <- left_join(play_data, count_data, by = "Pitcher")
pitcher_data <- left_join(pitcher_data, pitch_data[, c(1,8)], by = "Pitcher")
pitcher_data <- left_join(pitcher_data, inning_data, by = "Pitcher")

# Remove temp data frames
rm(count_data, play_data, pitch_data, inning_data)

## Fielding independent pitching (FIP)

# Compute FIP metric ∀ pitchers
pitcher_data <- pitcher_data %>% 
  mutate(
    FIP = (13*HomeRun + 3*(Walk + HitByPitch) - 2*Strikeout) / Innings + 4.22
  )

## Strikeouts per nine innings (K/9)

# Compute K/9 metric ∀ pitchers
pitcher_data <- pitcher_data %>% 
  mutate(
    K9 = (Strikeout / Innings) * 9
  )
```


